backend.py
frontend/src/App.tsx

Add basic grid layout

---

backend.py
frontend/src/App.tsx

Some molecules will not be valid for the current hard-coded values of `calc_spectrum()`.
Closes #9

Add all possible molecule options for calc_spectrum()

---

backend.py
frontend/src/App.tsx
frontend/src/components/WavelengthRangeSlider.tsx
frontend/src/constants.ts

Future TODO: Rename `constants.ts` as it's just containing an interface. Maybe `interaces.ts`? Not sure what's the norm.
Future TODO: Add validation such that max range cannot be smaller than min range.
Closes #12

Allow submitting the wavelength min and max from the frontend

---

backend.py
frontend/package.json
frontend/src/App.tsx
frontend/yarn.lock

Future TODO: Move `callCalcSpectrum()` inside of scope with the states so that setState doesn't need to be passed.
Closes #11

Handle no spectrum at the designated wavelength range

---

README.md

Add Actions Status + pre-commit badges

---

frontend/src/components/CalcSpectrum.tsx
frontend/src/components/WavelengthRangeSlider.tsx
frontend/src/constants.ts
frontend/tsconfig.json

Fix typing TODOs

---

frontend/src/components/CalcSpectrum.tsx
frontend/src/components/MoleculeSelector.tsx

Split MoleculeSelector component to its own module

---

frontend/src/components/CalcSpectrum.tsx

(simulated a 5 second load time on the backend to make it easy to see)
Closes #32

Add loading spinner when calculating the spectrum

---

backend.py
frontend/src/components/CalcSpectrum.tsx
frontend/src/components/MoleculeSelector.tsx
frontend/src/constants.ts
frontend/src/utils.ts

Add graph labels

---

backend.py
frontend/src/components/CalcSpectrum.tsx
frontend/src/utils.ts

Add pressure

---

backend.py
frontend/src/components/CalcSpectrum.tsx

Future TODOS:
- Make submission button disabled if there are any validation errors (potentially would be good to have a helper function to return if there are any validation errors to use to make the button disabled and to determine whether to submit)
- Change validation errors to allow for error messages, and figure out where to display them

Add super basic validation (no error messages, just red boxes)

---

backend.py
frontend/src/components/CalcSpectrum.tsx
frontend/src/components/SimulateSlit.tsx
frontend/src/components/WavenumberRangeSlider.tsx
frontend/src/constants.ts
requirements/prod.txt

Add Pydantic schema validation to the backend

---

frontend/src/App.tsx
frontend/src/components/CalcSpectrumPlot.tsx
frontend/src/constants.ts
frontend/src/utils.ts

I'm not sure the correct way, but I think this is better?

Remove UPPERCASE formatting for constants

---

backend.py
frontend/src/components/CalcSpectrum.tsx
frontend/src/constants.ts

Allow specifying gas temperature

---

frontend/src/components/CalcSpectrum.tsx

Add validation that Tgas must be between 70K and 3000K

---

frontend/src/components/CalcSpectrum.tsx
frontend/src/components/MoleculeSelector.tsx

Add molecule validation that it's a mandatory field

---

frontend/src/components/CalcSpectrum.tsx

Just removing `FormControl` as it isn't being used.
Closes #62

Fix multiple InputBase components inside of FormControl

---

frontend/src/components/CalcSpectrum.tsx
frontend/src/components/MoleculeSelector.tsx
frontend/src/components/WavenumberRangeSlider.tsx

Condense form fields

---

backend.py
frontend/src/components/CalcSpectrum.tsx
frontend/src/components/MoleculeSelector.tsx
frontend/src/components/WavenumberRangeSlider.tsx
frontend/src/constants.ts
tests/test_calc_spectrum.py

Add support for specifying vibrational temperature

---

frontend/src/components/CalcSpectrum.tsx
frontend/src/constants.ts
tests/test_calc_spectrum.py

Add support for specifying rotational temperature

---

frontend/src/components/CalcSpectrum.tsx
frontend/src/components/CalcSpectrumPlot.tsx
requirements/ci.txt
setup.cfg

Add wavenumber range selector to spectra plot

---

frontend/src/components/CalcSpectrum.tsx
frontend/src/components/ErrorAlert.tsx

Handle a bad backend response on the frontend

---

backend.py
frontend/src/components/CalcSpectrum.tsx
frontend/src/components/MoleculeSelector.tsx
frontend/src/components/Species.tsx
frontend/src/constants.ts
tests/test_calc_spectrum.py

Grouped molecule and mole fraction together as it's later planned to support specifying N species with varying mole fractions.

Add support for mole fraction

---

README.md

to give an idea of what it looks like and encourage people to try it and give feedback

added a WIP screenshot in the readme

---

src/components/CalcSpectrum.tsx
src/components/fields/Species.tsx
src/components/fields/WavenumberRangeSlider.tsx
src/index.css

https://user-images.githubusercontent.com/13723264/103466792-bc0fd580-4d0d-11eb-961c-62f27a8a6312.mov
Closes #146

Hide up/down arrows for number input

---

src/components/CalcSpectrum.tsx

https://user-images.githubusercontent.com/13723264/104110582-94d17f00-529e-11eb-9cde-5952eb8616aa.mov
Fixes #180

Fix plot wavenumber range updating dynamically

---

src/components/fields/MoleculeSelector.css
src/components/fields/MoleculeSelector.tsx

Not important but it looks nice 🙂 
https://user-images.githubusercontent.com/13723264/104111383-bf273a80-52a6-11eb-92b6-d36acb30b01b.mov
Closes #28

Format user molecule input to have subscripts

---

backend.py
src/components/CalcSpectrum.tsx
tests/test_calc_spectrum.py

https://user-images.githubusercontent.com/13723264/104112059-b1c27e00-52af-11eb-9d1a-65dd5bc225bf.mov
Let me know if there are any UI tweaks I can do related to this, eg. whether the option should be ordered differently.
Refs: #150

Add non-equilibrium calculations option

---

package.json
src/components/CalcSpectrum.tsx
src/components/fields/MoleculeSelector.tsx

Use proxy option in package.json

---

.github/workflows/main.yml
Makefile

Also remove Dockerfile build (which was commented-out anyway).

Move PORT=5000 to Makefile

---

src/components/CalcSpectrum.tsx
src/components/fields/MoleculeSelector.tsx
src/components/fields/Species.tsx
src/components/fields/WavenumberRangeSlider.tsx

Remove required field markers from interface

---

src/App.tsx
src/components/CalcSpectrum.tsx
src/components/CalcSpectrumPlot.tsx
src/components/ErrorAlert.tsx
src/components/fields/MoleculeSelector.tsx
src/components/fields/SimulateSlit.tsx
src/components/fields/Species.tsx
src/components/fields/WavenumberRangeSlider.tsx
src/components/fields/index.tsx

Switch from using default exports

---

.storybook/main.js
.storybook/preview.js
package.json
src/components/fields/MoleculeSelector/__stories__/MoleculeSelector.stories.tsx
src/components/fields/MoleculeSelector/index.tsx
yarn.lock

- Easier to develop as it makes it easy to focus on individual components
- Will help to enforce isolated components by exposing their interface; currently some components are not as isolated as they should be which makes it more difficult to develop (eg. `MoleculeSelector` requires passing all params instead of just the one it needs; there should be a nicer way to do it)

Add storybook and basic example with MoleculeSelector

---

src/components/CalcSpectrum.tsx
src/components/fields/MoleculeSelector/__stories__/MoleculeSelector.stories.tsx
src/components/fields/MoleculeSelector/index.tsx
src/components/fields/Species/index.tsx

I think it's better design to move all API calls to the container component and pass data to the children components.
Refs: https://stackoverflow.com/questions/58002674/parent-child-components-and-data-responsibilities-should-child-call-api

Move molecule options API call to container

---

src/components/fields/MoleculeSelector/__stories__/MoleculeSelector.stories.tsx
src/components/fields/MoleculeSelector/index.tsx
src/components/fields/Species/index.tsx

boring but needed code cleanup

Simplify MoleculeSelector interface

---

src/components/CalcSpectrum.tsx
tests/test_calc_spectrum.py

Extend Tgas constraint to 1K - 9000K

---

backend.py
setup.cfg

https://user-images.githubusercontent.com/13723264/115902449-11403600-a428-11eb-83b5-46f8793255e2.mov
Fixes #246

Display generic exception info to frontend (eg. OutOfBounds errors)

---

README.md
website/package.json
website/public/manifest.json
website/src/App.tsx

https://user-images.githubusercontent.com/13723264/122686448-a10b2200-d1d6-11eb-9ba8-37b81f67635a.mov
Closes #399

Add info popover with links to related sites

---

website/src/components/CalcSpectrum.tsx

change default Temperature to T=300 K  ( more useful ! )
change wmin-wmax range from 0:5000  to 500-10,000 cm-1   ( i.e. 1 - 20 µm, also more useful )

change defaults

---

lib/radis-lambda/app.py
website/src/App.tsx

add 1,2,3 isotopes by default

---

lib/radis-lambda/app.py
website/src/App.tsx

reduce payload size by resampling

---

lib/radis-lambda/app.py

Attempt to read predownloaded databases by copying generated radis.json from /root
Related to #476

Use predownloaded databases

---

website/src/components/CalcSpectrum.tsx
website/src/components/fields/WavenumberRangeSlider.tsx

This pull request is for the responsiveness of the. radis app, i use the breakpoint properties of the grid by MUI, so now the radis app is responsive so mobile users also use without any problems. it basically fixes the #362 .
Hey @suzil , @erwanp , please review the changes and give some feedbacks.😀

🚀 responsive mobileview of radis app

---

website/package.json
website/src/App.tsx
website/yarn.lock

Hey @suzil @erwanp, I add the GitHub logo and repo link.
Fixes #163 .

Github icon and repo link added 

---

website/src/components/fields/MoleculeSelector/index.tsx

Hey @erwanp, I correct the name.
Fixes #550.

correct the name

---

website/src/components/CalcSpectrum.tsx

Hey @suzil, please check I think now it is centred.
Fixes #549.

Center the spinner 

---

website/src/components/CalcSpectrum.tsx
website/src/components/fields/TRot.tsx
website/src/components/fields/TVib.tsx

Hey @suzil, I do the validation thing that doesn't allow negative values, please check 😀 .
Fixes #84 .

Add validation

---

website/src/App.tsx

Hey @suzil, please check this .
Fixes  #559 .

link added

---

server/.gitignore
server/download_geisa.py
server/download_hitran.py
server/main.py
server/requirements.txt

Thought I added this already but looks like I didn't.

Add server code

---

frontend/src/components/CalcSpectrum.tsx
frontend/src/components/CalcSpectrumPlot.tsx
frontend/src/components/fields/Mode.tsx
server/main.py

remove the mode bug 

---

frontend/src/components/CalcSpectrum.tsx

Fixing up  the `use_simulate_slit` bug
Reference : #620

Fixing  up the `use_simulate_slit` bug

---

server/download_hitemp.py
server/download_hitemp_CO2.py
server/download_hitemp_H2O.py

Add download_hitemp files

---

frontend/src/components/CalcSpectrum.tsx

fixed naming

---

frontend/src/components/CalcSpectrum.tsx
frontend/src/components/fields/Database.tsx
frontend/src/components/fields/MoleculeSelector/MoleculeSelector.tsx
frontend/src/components/fields/MoleculeSelector/molecules.ts
frontend/src/components/fields/Species/Species.tsx
server/main.py

This pull aims to add the hitemp database in radis-app interface.

adding hitemp in radis-app interface

---

server/main.py

Fix download API endpoint

---

frontend/src/components/CalcSpectrumPlot.tsx

Fixes #624
https://user-images.githubusercontent.com/73842340/186729508-73fc3697-7701-4377-8fcb-1da44ddcfcbb.mp4

Add the functionality to view the plotted  spectrum in log scale

---

frontend/src/components/DownloadSpecButton.tsx
frontend/src/components/DownloadTxtButton.tsx
frontend/src/components/Form.tsx
server/main.py

add the feature to download `txt` file in Radis App interface

---

frontend/src/components/Form.tsx

fixing download button bug

---

frontend/src/components/fields/WavenumberRangeSlider.tsx

fix the non-integer wavenumber value bug 

---

README.md

fix the indenting in the readme !!

fix the indenting in the  readme

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Adding issue templates

---

frontend/src/App.tsx

#573 fixes
Implemented Dark mode toggle feature.
Below attached screenshots of work:

#573 - Add Dark Mode Feature

---

paper/paper.md

Adding affliation
Review url - https://github.com/openjournals/joss-reviews/issues/5691#issuecomment-1653897613

adding affliation

---

frontend/src/components/fields/Species/Species.tsx

This PR fixes #711 
Before : 
https://github.com/user-attachments/assets/aa5735ea-fa46-4a0d-a447-1c069fb32d57
After : 
https://github.com/user-attachments/assets/fcf56591-359a-4822-a01f-1a9816a004bc

fix molecule selector validation bug

---

frontend/src/components/fields/WavenumberRangeSlider.tsx

fix: limit of wavelength slider

---

backend/src/helpers/logger_config.py

feat: update looger

---

frontend/src/components/CodeBlock.tsx
frontend/src/components/Form.tsx
frontend/src/components/Header.tsx
frontend/src/components/Settings.tsx
frontend/src/env.d.ts
frontend/src/store/form.ts

Run backend locally using Docker

---

backend/__tests__/helpers/payload_data.py
backend/src/helpers/calculateSpectrum.py
backend/src/helpers/fitSpectrum.py
backend/src/models/species.py
frontend/src/components/FitForm.tsx
frontend/src/components/Form.tsx
frontend/src/components/Info.tsx
frontend/src/components/fields/Species/Specie.tsx
frontend/src/components/fields/Species/Species.tsx
frontend/src/components/types.ts
frontend/src/modules/form-schema.ts
frontend/src/store/fitForm.ts

add all_isotopes option for molecules in both calc and fit forms
